name:                concur-core
version:             0.1.0.0
github:              "pkamenarsky/concur-core"
license:             BSD3
author:              "Philip Kamenarsky"
copyright:           "2022 Philip Kamenarsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pkamenarsky/concur-core#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- stm

library:
  source-dirs: src

tests:
  concur-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concur-core
